INSERT INTO user(id, email, password, gender, name, phone_number) VALUES (1L, 'testEmail@gmail.com', 'testPassword','M', 'testName','01099996384')
INSERT INTO user(id, email, password, gender, name, phone_number) VALUES (2L, 'updateTestEmail@gmail.com', 'testPassword','M', 'testName', '01099996384')
INSERT INTO user(id, email, password, gender, name, phone_number) VALUES (3L, 'deleteTestEmail@gmail.com', 'testPassword','M', 'testName', '01099996384')
INSERT INTO developer(id, name, notebook, monitor, keyboard, mouse) VALUES (1L, 'testName', 'testNotebook', 'testMonitor', 'testKeyboard', 'testMouse')
INSERT INTO developer(id, name, notebook, monitor, keyboard, mouse) VALUES (2L, 'testName', 'testNotebook', 'testMonitor', 'testKeyboard', 'testMouse')
INSERT INTO developer(id, name, notebook, monitor, keyboard, mouse) VALUES (3L, 'testName', 'testNotebook', 'testMonitor', 'testKeyboard', 'testMouse')